# In case any of these values is omitted, Kure will use the default one.
database:
  name: file_name
  path: absolute/path/to/folder

entry:
  format:
  - 1
  - 2
  - 3
  - 4
  - 5
  repeat: true

http:
  port: 4000

session:
  prefix: kure:~$
  timeout: 10m  # Leave blank for no timeout

# In this case, each iteration consumes 1024 MB (1 GB) of RAM, repeats the process 1 time and uses 6 threads.
#
# We higly recommend using the "kure config test" command to adapt them to your needs.
#
# Records encrypted using certain values won't be decryptable if they are changed later,
# this parameters should be set only once when starting to use Kure and never modified. Hovewer, we
# may include a command to allow re-encrypting records with new ones.
argon2:
  # Amount of memory allowed by algorithm. There is no "insecure" value for this parameter, though clearly the more memory the
  # better. The value is represented in kibibytes, 1 kibibyte = 1024 bytes. Default is 1048576 kibibytes (1 GB).
  memory: 1048576

  # Number of passes over the memory. The running time depends linearly on this parameter. We expect
  # that the user chooses this number according to the time constraints on the application. Again, there is
  # no "insecure value". Default is 1.
  iterations: 1

  # Number of threads running in parallel. Default is the maximum number of logical CPUs usable.
  threads: 6 # This number is representative