database:
  path: path/to/file
  name: kure

user:
  password: your-password-hash     # OR password_path: path/to/file

entry:
  format: 
  - 1
  - 2
  - 3
  - 4
  - 5
  repeat: true

http:
  port: 4000