name: Lint
on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Linter
      uses: morphy2k/revive-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}